/** Shared column headers for Central Stock download and stock import. */
export const STOCK_EXPORT_HEADERS = [
  "Item Code",
  "Product",
  "SKU",
  "Category",
  "Metal",
  "Purity",
  "Weight (g)",
  "Stone (ct)",
  "Making Charges",
  "Price",
  "Price Source",
  "Status",
  "Location",
  "Ageing (days)",
  "Transferred Date",
  "Created Date",
] as const;

/** Legacy import columns still accepted via header aliases. */
export const LEGACY_STOCK_EXCEL_HEADERS = [
  "Stock Type",
  "HSN",
  "SKU NO",
  "Item no/ Barcode",
  "Status",
  "Item Description",
  "Category",
  "Sub-Category",
  "Collection",
  "Website Status",
  "Vendor Name",
  "Metal",
  "Purity",
  "Wt Gross",
  "Wt Net",
  "Wt Other",
  "Stone Name",
  "Wt Stone",
  "Color Stone",
  "Retail Price",
  "Cost",
  "Active Date",
  "Current Location",
  "Item Remarks",
] as const;
