import { writeFileSync } from "fs";
import { generateTransferInvoicePdf } from "../src/lib/invoices/transfer-invoice-pdf.js";
import type { ShopSettings } from "../src/types.js";

const settings: ShopSettings = {
  businessName: "TRIBE Amrapali",
  address: null,
  addressLine1: "Plot No. A-260, Housing Colony",
  addressLine2: "RIICO, Sitapura Industrial Area",
  city: "Jaipur",
  state: "Rajasthan",
  pincode: "302022",
  country: "India",
  phone: "+91 9876543210",
  email: "sales@tribeamrapali.com",
  upiVpa: null,
  panNumber: "AAFCT5189D",
  gstNumber: "08AAFCT5189D1Z4",
  cinNumber: "U36911RJ2015PTC048477",
  gstRegisteredName: null,
  goldHsnCode: "7113",
  silverHsnCode: "7113",
  imitationHsnCode: "71179010",
  invoiceTerms:
    "Goods once sold will not be taken back. Subject to Jaipur jurisdiction only.",
  registeredOfficeAddress:
    "Plot No. A-260, Housing Colony, RIICO, Sitapura Industrial Area, Tonk Road, Jaipur - 302022",
  bankAccountName: null,
  bankAccountNumber: null,
  bankIfsc: null,
  bankName: null,
  goldMakingChargesPct: 17,
  silverMakingChargesPct: 17,
  makingChargesOverrideNote: null,
};

const transfer = {
  id: "test",
  transferNo: "TR-001",
  fromBranchId: "b1",
  toBranchId: "b2",
  customerId: "c1",
  customerBranchId: null,
  documentType: "Wholesale GST Invoice",
  transferDate: new Date("2026-07-01"),
  itemCount: 2,
  totalValue: 1189527,
  status: "Accepted" as const,
  acceptedById: null,
  acceptedByName: null,
  acceptedAt: null,
  rejectionReason: null,
  notes: null,
  recipientGstNumber: "27AABCU9603R1ZM",
  recipientGstRegisteredName: null,
  recipientPanNumber: "AABCU9603R",
  recipientEmail: null,
  recipientPhone: null,
  recipientAddress: "Mumbai, Maharashtra",
  placeOfSupplyState: "Maharashtra",
  placeOfSupplyStateCode: "27",
  placeOfDeliveryState: "Maharashtra",
  placeOfDeliveryStateCode: "27",
  contactPersonName: "Raj",
  contactPersonPhone: "9999999999",
  courierCompany: "BlueDart",
  dispatchDate: new Date("2026-07-02"),
  invoiceNo: "INV-2026-001",
  invoicedAt: new Date("2026-07-02"),
  createdById: null,
  createdByName: "Admin",
  createdAt: new Date("2026-07-01"),
  customer: { name: "Wholesale Buyer Pvt Ltd" },
  customerBranch: null,
  items: [
    {
      id: "1",
      transferId: "test",
      itemCode: "I1",
      productId: "p1",
      productName: "Ring",
      sku: "SKU1",
      metal: "Base Metal",
      purity: "925",
      price: 500000,
      accepted: true,
      weightGrams: 1200,
    },
    {
      id: "2",
      transferId: "test",
      itemCode: "I2",
      productId: "p2",
      productName: "Necklace",
      sku: "SKU2",
      metal: "Gold",
      purity: "22K",
      price: 689527,
      accepted: true,
      weightGrams: 850,
    },
  ],
};

const pdf = await generateTransferInvoicePdf(
  transfer as Parameters<typeof generateTransferInvoicePdf>[0],
  settings,
  "Rajasthan",
);
writeFileSync("test-wholesale-invoice.pdf", pdf);
console.log(`Wrote test-wholesale-invoice.pdf (${pdf.length} bytes)`);
