-- AlterTable
ALTER TABLE "ShopSettings" ADD COLUMN IF NOT EXISTS "email" TEXT;
ALTER TABLE "ShopSettings" ADD COLUMN IF NOT EXISTS "cinNumber" TEXT;
ALTER TABLE "ShopSettings" ADD COLUMN IF NOT EXISTS "goldHsnCode" TEXT DEFAULT '7113';
ALTER TABLE "ShopSettings" ADD COLUMN IF NOT EXISTS "silverHsnCode" TEXT DEFAULT '7113';
ALTER TABLE "ShopSettings" ADD COLUMN IF NOT EXISTS "imitationHsnCode" TEXT DEFAULT '71179010';
ALTER TABLE "ShopSettings" ADD COLUMN IF NOT EXISTS "invoiceTerms" TEXT;
ALTER TABLE "ShopSettings" ADD COLUMN IF NOT EXISTS "registeredOfficeAddress" TEXT;
